<?php

/**
 * @file
 * Functions to support theming in the SASS Starterkit subtheme.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_system_theme_settings_alter() for settings form.
 *
 * Replace Barrio setting options with subtheme ones.
 *
 * Example on how to alter theme settings form
 */
function covid_form_system_theme_settings_alter(&$form, FormStateInterface $form_state) {
  $form['components']['navbar']['bootstrap_barrio_navbar_top_background']['#options'] = [
    'bg-primary' => t('Primary'),
    'bg-secondary' => t('Secondary'),
    'bg-light' => t('Light'),
    'bg-dark' => t('Dark'),
    'bg-white' => t('White'),
    'bg-transparent' => t('Transparent'),
  ];
  $form['components']['navbar']['bootstrap_barrio_navbar_background']['#options'] = [
    'bg-primary' => t('Primary'),
    'bg-secondary' => t('Secondary'),
    'bg-light' => t('Light'),
    'bg-dark' => t('Dark'),
    'bg-white' => t('White'),
    'bg-transparent' => t('Transparent'),
  ];
}

/**
 * want to target field--text-with-summary.html.twig
*/
// function covid_preprocess_field() {

// }

/**
* Implements hook_preprocess_HOOK() for menu.html.twig.
*/
function covid_preprocess_menu(&$variables) {
  if ($variables['menu_name'] == 'main') {
    // if there is not an existing class array, create an empty array.
    if (!isset($variables['attributes']['class'])) {
      $variables['attributes']['class'] = [];
    }
    // Merge with any classes that may have been set by other hook_preprocess_menu invocations
    $variables['attributes']['class'] = array_merge($variables['attributes']['class'], ['my-main-menu', 'my-navigation']);
  }
}